site_name: TimeLine Developer
nav:
  - Documentation:
    - Introduction: documentation/introduction.md
  - Best Practices:
    - Coding Style: bestpractices/coding-style.md
  - MkDocs: mkdocs/using-mkdocs.md
