site_name: TimeLine Developer
nav:
  - Home: index.md
  - Documentation:
    - Introduction: documentation/introduction.md
  - Best Practices:
    - General: bestpractices/general.md
    - Code Smells: bestpractices/code-smells.md
  - MkDocs: mkdocs/using-mkdocs.md
